version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
